# Generated by Django 5.1 on 2025-12-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('service', models.CharField(blank=True, choices=[('smm-strategy', 'SMM стратегия'), ('content-creation', 'Создание контента'), ('ai-content', 'AI контент'), ('analytics', 'Аналитика и отчеты'), ('consultation', 'Консультация')], max_length=50, verbose_name='Услуга')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Отправлено в Telegram')),
                ('telegram_message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
