# Generated by Django 5.1 on 2026-01-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
