# Generated by Django 5.1 on 2026-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('smm', 'SMM'), ('content', 'Контент & Reels'), ('target', 'Таргет')], max_length=20, verbose_name='Категория')),
                ('niche', models.CharField(help_text='Например: E-commerce, Личный бренд', max_length=100, verbose_name='Ниша / Тег')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Изображение')),
                ('metric_value', models.CharField(help_text='Например: +150%', max_length=50, verbose_name='Значение метрики')),
                ('metric_label', models.CharField(help_text='Например: Продажи', max_length=50, verbose_name='Подпись метрики')),
                ('secondary_value', models.CharField(help_text='Например: 3 мес', max_length=50, verbose_name='Вторая метрика')),
                ('secondary_label', models.CharField(help_text='Например: Срок', max_length=50, verbose_name='Подпись второй метрики')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('niche', models.CharField(help_text='Например: Бьюти мастер', max_length=100, verbose_name='Ниша')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/avatars/', verbose_name='Аватар')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('result', models.CharField(help_text='Например: +1500 подписчиков за месяц', max_length=200, verbose_name='Результат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
